### ISSUE TITLE
Add villager split on resource rather than timings

### ISSUE THREAD

**Issue by LENpolygon** [LENpolygon/Build-Order-Tool-AoE4-#12]
Suggestion by DrDabston on Reddit:

> One thing that I would suggest is rather than having timings having a nice pretty look for vill split on resources. You can see how i chose to do it rather than timings. It gets difficult updating the time for each villagers (a lot of times to make it clean you say 4 onto gold) so then that would be 1 min 20 seconds unless you are french and then it will depend age or if you are chinese song dynasty. Also builds will always vary by seconds and sometimes more. I like having the benchmark times in there for the big events such as age up or tech up or song dynasty but feel it is less necessary for the whole entire build.

**Comment by LENpolygon** [comment]
Maybe this should be a switchable/alternate option somehow?

**Comment by LENpolygon** [comment]
Similar suggestion by o118899nine on Reddit:

> Maybe add an option to add an extra column to show villager distribution the way I did here.

**Comment by LENpolygon** [comment]
Idea as follows:

- Seperate columns for all 4 resources
- Can only enter whole numbers in columns (?)
- If number is different from previous row then background/number lights up to more easily see changes between rows

!

**Comment by drewdunne** [comment]
My partner is a UX designer - I can ask her opinion on how to format it if you'd like @LENpolygon.

I would definitely say the villager split is top-priority for some people. For ex: Grubby actually makes the villie split take up more than half the visual space in his build order graphics:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/57418947/167239301-159f626f-7c28-4f74-a8e6-0f6ebb842033.png">

https://www.youtube.com/watch?v=AnGwrVk-lI0

**Comment by LENpolygon** [comment]
Hi, drewdunne, thanks for your comment and example! Would be awesome to have some help on this. 

Please do ask her opinion, I currently have this idea in mind:

![image](https://user-images.githubusercontent.com/97443666/167245660-bc167b0f-4981-49dc-b667-05fa5cc53252.png)

Per step you can see vill distribution. And when the number changes from previous step it gets highlighted to also indicate more easily on "what" you should focus next / where next villagers should be rallied.

Any advise/ideas/code is welcome!

**Comment by drewdunne** [comment]
Hey @LENpolygon - talked it over w/ the partner. She hasn't used an RTS build order before, so gonna walk through a few of those and then reevaluate!

**Comment by LENpolygon** [comment]
> Hey @LENpolygon - talked it over w/ the partner. She hasn't used an RTS build order before, so gonna walk through a few of those and then reevaluate!

Cheers, looking forward to your replies!

**Comment by LENpolygon** [comment]
Implemented a first version. Updates or ideas to improve are still welcome!

![image](https://user-images.githubusercontent.com/97443666/168418905-bdec38a9-2392-40e0-ab31-a09b3d5ef12c.png)
