### ISSUE TITLE
Small "database" showing the most popular builds.

### ISSUE THREAD

**Issue by LENpolygon** [LENpolygon/Build-Order-Tool-AoE4-#4]
Small database capturing all the recent builds, allow people to LIKE/DISLIKE builds somehow, then show the top builds in a sub-menu for each civ.

**Comment by dlearningfr** [comment]
Hey man, I'd like to help you with that, do you have any idea how you would set this up at minimal cost ?

**Comment by Hayanno** [comment]
Hey man, I'd like to help you with that.

Do you have any idea how you would set this up ?

I'm thinking just putting data inside a database (to be determined which one, also depending on your hosting).

I can make a pull request once you tell me how you would like it done.

**Comment by LENpolygon** [comment]
That's awesome, thanks for the offer!

I have very little knowledge about all the database options out there. The site is hosted on Firebase now, so perhaps their "Realtime Database" can be used?

Have thought a bit about how to show the most "popular builds" but no sure there either because a build with a lot of upvotes can be very outdated, a build with 100% like-dislike ratio can only have 1 vote, etc... Also, you don't want a single person to be able to spam votes on  a single build and destroy the system. There are probably good algorithms out there to determine if a build is popular + recent + relevant. 

If you want me to do some more research in one of these subject then let me know and I'll look into it!

**Comment by Hayanno** [comment]
I don't know much about Firebase, never used it, I don't know their prices and what a "realtime database" can offer.
I found this : https://github.com/typicode/lowdb which use a simple file as a database, so depending on our need it could be really fast to implement, but it means : poor performance, poor scalability and poor security.
If we want to use an SQL database to build something more robust we will need a PHP backend to query it, does your hosting support it ?
Either option are fine by me, it depends on how you see the project growing.

About the ranking algorithm, I have to say that I followed a very interesting path, and I found this : https://github.com/msn0/wilson-score-interval which is the algorithm used by reddit (https://www.npmjs.com/package/wilson-score) I think I can implement it pretty easily. I don't understand everything about the math behind it, but I'm getting the idea and I think it would work great.
I found this answer on SO : https://stackoverflow.com/questions/7183807/ranking-algorithm-based-on-upvotes-and-views-without-downvotes and I think the idea to only count for the last week upvote would means that we don't have outdated build, I still don't know about that last part, because I think some builds don't change much over time.
We could also offer the possibility to sort by new (so new post don't get burried), popular (so we have the overrall best build) or trending (for the latest trend).

**Comment by LENpolygon** [comment]
Those are some great ideas!!

> I found this : https://github.com/typicode/lowdb which use a simple file as a database, so depending on our need it could be really fast to implement, but it means : poor performance, poor scalability and poor security.

This is the perfect solution for now I think. Sounds easy to set up, and we're not storing any personal data, just:

- The build
- Build Name (this will be a new item that I'll add near the top of the "Build Order table "
- Date of creation
- Ranking score

> About the ranking algorithm, I have to say that I followed a very interesting path, and I found this : https://github.com/msn0/wilson-score-interval which is the algorithm used by reddit (https://www.npmjs.com/package/wilson-score) I think I can implement it pretty easily. I don't understand everything about the math behind it, but I'm getting the idea and I think it would work great.

Sounds great too. I think the Reddit system is good, just not sure if we'll have enough data to make it work, but it it's easy enough to implement then we can test it. For sure.

> I found this answer on SO : https://stackoverflow.com/questions/7183807/ranking-algorithm-based-on-upvotes-and-views-without-downvotes and I think the idea to only count for the last week upvote would means that we don't have outdated build, I still don't know about that last part, because I think some builds don't change much over time.

True, most builds won't change much, but I believe the popularity can vastly change over time. A few weeks ago the Fire Lancer rush was THE most popular build in team games, but since the nerf it's been much less popular, so it would probably receive less upvotes/views and more downvotes.

> We could also offer the possibility to sort by new (so new post don't get burried), popular (so we have the overrall best build) or trending (for the latest trend).

Good suggestion. Regarding the front end I want to make it like this:

- User clicks on civilization
- Instead of "Build Order table" show the Builds for this civ.
- Builds for this civ is divided in two columns/div's: Most Popular & Newest
- Each column has a limit of 10-20 items
- Each item shows: Build Name, Build Date, Popularity score
- After clicking on a item it redirects to the specific build.
- From the Build window you can upvote/downvote it & edit it.
- As soon as build is edited then the upvote/downvote is gone.
- As soon as the edited build gets Saved then it gets added to the database and the upvote/downvote is back.

There are probably some things that need a bit tweaking, but hope it makes sense. Let me know if you have any other suggestions to add.

I have a busy weekend, but after that I can start working on the front end. I must say that I've never really used Github and am unfamiliar with the whole push/pull system, but I'll read into it and look forward to working together with you!! :-)

**Comment by JPratt417** [comment]
Not sure how you're progressing on this, but if you need some additional help I'd be happy to chip in. I'm a professional full stack developer with about 5 years of experience, so whatever needs more work (front end vs back end) I'd be happy to chip in.

**Comment by Hayanno** [comment]
I'm traveling right now, I'll be back 21 of february, I didn't have time to implement what we said in this issue, if you would like to propose something it would be welcome I think, I could take a look when I come back and help you if you need.

**Comment by LENpolygon** [comment]
Hi JPratt417, 

Forgive me for being a complete amateur; I had to Google what tech stack means and I'm still not sure. I'll just let you know how the project is made so far:

- HTML, CSS, Vanilla JS (no JQuery or anything like that)
- Most of it is on the index.html page (it's mostly JS)
- 1 external JS script which is only for string compression and decompression
- All data-files so far are static JSON files
- Entire thing is made in Visual Code, no fancy external editors
- Webpage is hosted on Firebase
- I use Analytics to track 
- No database has been selected, but together with the options from Hayanno the options are:

1. https://github.com/typicode/lowdb (advantage: hosting independant)
2. Cloud Firestore (by Firebase)
3. Realtime Database (by Firebase)

Here's the comparison between the Firebase options: https://firebase.google.com/docs/database/rtdb-vs-firestore?authuser=3

I hope any of this helps. If you have specific questions let me know, or we could even organize a call via Teams/Discord.

**Comment by LENpolygon** [comment]
Hi @JPratt417 and @Hayanno ! 

Do any of you feel up to this task or any advice on how to proceed? Looking forward to your replies.

**Comment by xarvey** [comment]
Is anyone still working on this? If not I can give it a shot.

**Comment by LENpolygon** [comment]
Closed for now. Still looking for upgrades to current system.
