### ISSUE TITLE
Making Column Headers Sticky when scrolling

### ISSUE THREAD

**Issue by davidgamero** [LENpolygon/Build-Order-Tool-AoE4-#44]
Currently the column headers disappear when scrolling down a build order's rows, and making them sticky would improve readability when further down into a build order

## Example of when they disappear:
![image](https://user-images.githubusercontent.com/4248857/209482094-48e62699-cdc5-4a3b-bd30-a19460c3a3c2.jpeg)

## Example of ideal sticky location for headers (i just scrolled to where they line up to illustrate):
![image](https://user-images.githubusercontent.com/4248857/209482103-953a55fe-9e42-403c-b766-71144f26ac62.jpeg)

**Comment by LENpolygon** [comment]
Added and uploaded; great suggestion!
